1_Multidimensional_NumPy_Arrays
- Mathematical_Objects:
- Scalar (0D), Vector (1D), Matrix (2D), Tensor (XD Where x > 2)

In [2]:
import numpy as np

scalar = np.array(90) # 0D
vector = np.array(
    [1, 2, 3]  # 1D
)

metrix = np.array(
    [ [1, 2, 3], 
    [4,5,6],
    [7,8,9] ] #2D
)

tensor = np.array(
    [[[[1]]]]  # 4D
)

print('Sclar:', scalar)
print('Dimension:', scalar.ndim)

print('vector:', vector)
print('Dimension:', vector.ndim)

print('Metrix:', metrix)
print('Dimension:', metrix.ndim)

print('Tensor:', tensor)
print('Dimension:', tensor.ndim)


Sclar: 90
Dimension: 0
vector: [1 2 3]
Dimension: 1
Metrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension: 2
Tensor: [[[[1]]]]
Dimension: 4


2_Numpy_Indexing

In [25]:
my_1d_array = np.array(
    [1, 2, 3, 4]
)

print(my_1d_array[0])
print(my_1d_array[-4])

my_2d_array = np.array(
    [[1, 2, 3, 4], # 0 -3
    [5, 6, 5, 8], # 1  -2
    [9, 6, 4, 1]] # 2 -1
)

print(my_2d_array[1,2])
print(my_2d_array[-2,-2]) # nagative_indexing

1
1
5
5


In [28]:
my_3d_array = np.array(
    [
        [
            [1, 2 ],
            [5, 6 ],
        ]
    ]
) 

my_3d_array.shape 
# 1*2*2  Note: 1--> There_is_1_block, 2--> 2_rows_in_each_ block 2---> 2_elements in_each_row

(1, 2, 2)

In [39]:
my_3d_array = np.array(
    [
        [ # 1st_block
            [1, 2 ],
            [3, 4 ],
        ],
        [ # 2nd_block
            [5, 6],
            [7, 8 ],
        ]
    ]
) 

my_3d_array.shape
# 2*2*2 Note: 2_layers/block (depth = 2), 2_rows_in_each_layer , 2_elements_in_each_row

my_3d_array[1][0][1] # Note: 2nd_block → [1] , block_1st _row → [0], row_2nd_element → [1]
my_3d_array[-1][0][-1] # nagative_indexing

np.int64(6)

3_Numpy_Slicing
- arguments_with_default_values: start=0, stop_n, step=1
- array_name [start:stop:step]
- end_index_is_excluded

In [53]:
my_1d_array = np.array(
    [1, 2, 3, 4, 5, 6 ]
)

print(my_1d_array [1:4]) # 2, 3, 4
print(my_1d_array [0:7]) # 1, 2, 3, 4, 5, 6

print('1st_first_5_ta_digit:' ,my_1d_array[:5]) # 1, 2, 3, 4, 5
print('1st 3_digit_por_baki_gula:' ,my_1d_array[3:]) # 4, 5, 6

print('Every second character:', my_1d_array[::2]) # 1 3 5

print('Reverses the string ', my_1d_array [::-1]) 
print('Reverses the string ', my_1d_array [::-4])


print('Array:', my_1d_array)
print(my_1d_array[1:4:1]) # 2,3,4

print(my_1d_array[1::2]) #  2 4 6


[2 3 4]
[1 2 3 4 5 6]
1st_first_5_ta_digit: [1 2 3 4 5]
1st 3_digit_por_baki_gula: [4 5 6]
Every second character: [1 3 5]
Reverses the string  [6 5 4 3 2 1]
Reverses the string  [6 2]
Array: [1 2 3 4 5 6]
[2 3 4]
[2 4 6]


In [5]:
my_2d_array = np.array(
    [[1, 2, 3, 4], # 0 -3
    [5, 6, 5, 8], # 1  -2
    [9, 6, 4, 1]] # 2 -1
)

print(my_2d_array[0:2, 1:3]) 


[[2 3]
 [6 5]]


4_Numpy_reshape: Changing_the_shape_of_an_array

- Condition: Number_of_elements_must_be_same .
- Flatten_the_original_array:
- [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
- Reshape_as_desired_shape:
- [[[1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]

In [7]:
my_2d_array = np.array(
    [[1, 2, 3, 4, 1], # 0 -3
    [5, 6, 5, 8, 12], # 1  -2
    [9, 6, 4, 1, 13]] # 2 -1
)

print(my_2d_array.shape)
my_2d_array_reshaped = my_2d_array.reshape(1, 3, 5)
print(my_2d_array_reshaped)
print(my_2d_array_reshaped.shape)


(3, 5)
[[[ 1  2  3  4  1]
  [ 5  6  5  8 12]
  [ 9  6  4  1 13]]]
(1, 3, 5)


5_Numpy_Filtering

In [10]:
my_1d_array = np.array(
    [1, 2, 3, 4]
)

filter_mask = [True, False, True, False]
filtered_array = my_1d_array[filter_mask]
print(filtered_array)

indices = [0,2,3]
filtered_array = my_1d_array[indices]
print(filtered_array)


[1 3]
[1 3 4]


6_Vectorization_refers_to_the_process_of_performing_operations
- Process_each_operation_perallely
- 1%2 2%2  3%2 4%2
-  1   0    1   0
-  [1, 0, 1, 0,1]

In [11]:
my_1d_array = np.array(
    [1, 2, 3, 4]
)
my_1d_array = my_1d_array % 2
print(my_1d_array)

[1 0 1 0]


6_Broadcasting
- Converts smaller-shaped arrays to match larger ones for vectorized operations.
- Rule: Shapes are compatible if each dimension is equal or one is 1.
- Example:
(6, 7) and (6, 1) → ✅ Compatible
(6, 7, 8) and (1, 7, 8) → ✅ Broadcasting possible

In [ ]:
w = np.array(
    [1, 2],
)

x = np.array([
    [3, 4], 
    [5, 6],
    [7, -8],
    [-5, -3]
])

# Vectorization:
#  [3, 4],          [5, 6],    [7, -8],        [-5, -3]
#   [1, 2],          [1, 2],    [1, 2],        [1, 2],
#  [3, 8]            [5, 12]    [7, -16]       [-5, -6]
print(w * x)

# Step 1: Match the dimensions of the arrays
# Step 2: Duplicate the mismatch dimension items to match the higher dimensional array shape
print(w.reshape(1, 2).shape)
x.shape

w = [[1, 2],
     [1, 2],
     [1, 2],
     [1, 2]]
print(w * x)


7_Numpy axis 

- First dimension: axis=0
- Second dimension: axis=1
- Third dimension: axis=2
- Nth dimension: axis=N-1
- Aggregation function: sum, min, max, median


In [3]:
my_np_array = np.array(
    [
        [1, 5, -2],
        [0, 1, 9]
    ]
)

sum_all_elements = np.sum(my_np_array)
print(sum_all_elements)
print(my_np_array.shape)

sum_row_wise = np.sum(my_np_array, axis=1)
print(sum_row_wise)

sum_row_wise = np.sum(my_np_array, axis=0)
print(sum_row_wise)
print(sum_row_wise.shape)

my_np_3d = np.zeros(
    shape=(3, 2, 2)
)

# np.sum at axis=0,
#    element 1: [[2, 2], 
#               [1, 1]]
#    element 2: [[3, 1],           
#               [4, 3]]
#    element 3: [[9, -2], 
#               [1, 1]]

print(np.sum(my_np_3d, axis=0).shape)
print(np.sum(my_np_3d, axis=1).shape)
print(np.sum(my_np_3d, axis=2).shape)

14
(2, 3)
[ 4 10]
[1 6 7]
(3,)


8_numpy random 

- rand(): returns a random value between [0, 1]
- randint(x): returns a random value between [0, x) 
- randint(x, size): returns a random array between [0, x) of size
- shuffle(): shuffle an array

In [ ]:
print(np.random.rand())
print(np.random.rand(2, 5))

print(type(np.random.rand(5)))
print(np.random.randint(100))

my_array = np.random.randint(100, size=(5,2))
print(my_array)

np.random.shuffle(my_array)
print(my_array)


9_Useful_methods

In [ ]:
probabilities = np.array([0.3, 0.1, 0.4, 0.2])

probabilities_sorted = np.sort(probabilities)
print(probabilities_sorted)

probabilities_reverse_sorted = np.sort(probabilities)[::-1]
print(probabilities_reverse_sorted)

10_Argmax_Argmin

In [ ]:
index_max = np.argmax(probabilities)
print(index_max)

index_max = np.argmin(probabilities)
print(index_max)

11_Split 

In [ ]:
my_np_array = np.array([1, 5, 1, 1, 5, 7])

new_np_array = np.split(
    my_np_array, 
    indices_or_sections=3
)
print(new_np_array)
print(new_np_array[0])
print(new_np_array[1])
print(new_np_array[2])


my_np_array_1 = np.array(
    [1, 2, 3]
)

my_np_array_2 = np.array(
    [3, 4, 3]
)

print(my_np_array_1)
print(my_np_array_2)

dot_product = np.dot(my_np_array_1, my_np_array_2)
print(dot_product)

12_matrix_transpose

In [ ]:
my_2d_array_1 = np.array(
    [[2, 1, 3],
     [7, 5, 6]]
)

print(my_2d_array_1.shape)
print(my_2d_array_1.T)
print(my_2d_array_1.T.shape)

print(my_np_array_1)

print(np.mean(my_np_array_1))
print(np.median(my_np_array_1))
print(np.std(my_np_array_1))